Tree algorithms
budkovmm/cslessons pull request #3
Opened 2024-04-03 21:15 UTC by budkovmm

1. Вычислить глубину бинарного дерева
2. Найти количество правых листьев в бинарном дереве. Листья - это узлы, не имеющие потомков
3. Реализовать вставку бинарного дерева в заданное бинарное дерево на заданное место. Способ вставки - левым потомком. "Старое" левое поддерево вставить слева в крайний левый элемент добавляемого дерева.

2024-04-07 19:48 UTC, sov-87 requested changes

2024-04-07 19:48 UTC, sov-87 commented on trees/treeDepth.go
> +		return -1
здесь минус один, а потом прибавляем единицу. довольно странно.

2024-04-10 11:03 UTC, sov-87 commented on trees/main.go
> +	treeForInsert := node(6)
в одном mr лучше не мешать новые задачи и исправления других задач

2024-04-10 11:29 UTC, budkovmm commented on trees/main.go
> +	treeForInsert := node(6)
я немного запутался, в одном МРе или коммите?
в этом МРе делаю всё что касается задач из https://github.com/budkovmm/cslessons/issues/2
> Реализовать вставку бинарного дерева в заданное бинарное дерево на заданное место. Способ вставки - левым потомком. "Старое" левое поддерево вставить слева в крайний левый элемент добавляемого дерева.

2024-04-13 08:05 UTC, sov-87 approved these changes

2024-04-13 08:42 UTC, merged