Задачи на списки
budkovmm/cslessons pull request #6
Opened 2024-04-12 14:18 UTC by budkovmm

1. Реализовать динамический массив с использованием односвязного списка. Должны быть методы вставки элемента на заданное место и вырезки элемента по заданному индексу.
2. Сделать предыдущее задание с использованием двусвязного списка.
3. Написать программу, которая моделирует вставку и удаление элементов. В самом начале программы создать массив из 100 000 элементов. Удаление и добавление производить случайным образом в доступном диапазоне индексов. Моделировать 100 000 операций. Сравнить скорость работы программы для двух разных реализаций.

2024-04-13 04:13 UTC, sov-87 requested changes

2024-04-13 04:13 UTC, sov-87 commented on lists/dynamicArray.go
> +функция вырезатьЭлементПоИндексу(i число)
откуда вырезаем? этот же вопрос к функции в программе

2024-04-13 05:37 UTC, budkovmm commented on lists/dynamicArray.go
> +функция вырезатьЭлементПоИндексу(i число)
поправил. в программе используется метод структуры List, который используя pointer receiver изменяет список

2024-04-17 13:22 UTC, sov-87 requested changes

2024-04-17 13:22 UTC, sov-87 commented on lists/linkedList_test.go
> +func BenchmarkDoublyLinkedList(b *testing.B) {
посмотри внимательнее задание, там сказано, что вставка или удаление должны выбираться случайно. то есть 100 000 операций, каждую конкретную операцию надо моделировать случайным числом.

поскольку длина списка будет меняться случайным образом, константу для хранения длины использовать нельзя.

2024-04-22 08:51 UTC, sov-87 approved these changes

2024-04-22 09:23 UTC, merged